config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :jobs
  resources :organizations
  root 'jobs#index'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  belongs_to :organization

  JOB_TYPES = ['Full-time', 'Part-time', 'Contract', 'Freelance']
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :jobs
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :jobs
  has_many :organizations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  before_action :authenticate_user!, except: %i[index show]
  before_action :set_job, only: %i[show edit update destroy]

  # GET /jobs.json
  def index
    @jobs = Job.all.order("created_at DESC")
  end

  # GET /jobs.json
  def show
  end

  # GET /jobs/new
  def new
    @job = current_user.jobs.build
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = current_user.jobs.build(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Your job was created successfully!' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end

  rescue Stripe::CardError => e
    flash.alert = e.message
    render action: :new
  end

  # PATCH/PUT /jobs/1
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Your job was updated successfully!.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Your job was destroyed successfully!.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_job
    @job = Job.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def job_params
    params.require(:job).permit(:title,
                                :description,
                                :level,
                                :job_type,
                                :location,
                                :remoteable,
                                :apply_url,
                                :is_published)
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  before_action :authenticate_user!, except: %i[index show]
  before_action :set_organization, only: %i[show edit update destroy]

  # GET /organizations.json
  def index
    @organization = Organization.all
  end

  # GET /organizations.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = current_user.organizations.build
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = current_user.organizations.build(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Your organization was created successfully!' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Your organization was updated successfully!.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Your organization was destroyed successfully!.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_organization
    @organization = Organization.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def organization_params
    params.require(:organization).permit(:name,
                                :status,
                                :address,
                                :country,
                                :tax_code,
                                :ot_policy,
                                :description,
                                :landing_page,
                                :company_type,
                                :company_size,
                                :working_days,
                                :short_description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_form.html.erb
<header>
  <img src="https://smocca-staging.zigexn.vn/assets/smocca/cashback/20231101/default/banner_cp760_01-732186c4f4dd31286d95194f1af2d5eb.png" alt="cashback">
</header>
<br><hr/>

<section class="d-flex flex-column bd-highlight mb-3">
  <h5>お問い合わせ内容・ご連絡先</h5>
  <br>
  <div class="flext-row">
    <span>1.入力フォームに記入</span>
    <span>  >  </span>
    <span>2.入力情報の確認</span>
    <!--    <ul>-->
    <!--      <li>-->
    <!--        <span>1.入力フォームに記入</span>-->
    <!--      </li>-->
    <!--      <li>-->
    <!--        <span>2.入力情報の確認</span>-->
    <!--      </li>-->
    <!--    </ul>-->

  </div>
  <br>
  <div class="flex-row">
    <span>残り</span>
    <span>2</span>
    <span>ステップ完了でお問い合わせ！</span>
  </div>
  <br>

  <div class="flex-row">
    <span>オススメ</span>
    <span>LINEで必要項目を自動入力する</span>
  </div>
  <br>

  <div>
    <a href="https://autoline.link/smocca/apis/line_login_link?register_from=others&amp;redirect_url=https%3A%2F%2Fsmocca-staging.zigexn.vn%2Fapply%3Fglobal_keys%255B%255D%3Dz_2_1da2fd88bead89467624616417c0c301%26recommend_type%3Dbase_search_pr&amp;timetech_code=xpfonvm6" id="js-efo-line_social_login">
      <img src="https://smocca-staging.zigexn.vn/assets/smocca/pc/line_login_button-920158ae6eecf01e08ecc6b19d9688bb.png" alt="LINEでログイン">
    </a>
    <p>※LINEログインを使うと必須項目を自動入力できます</p>
  </div>
  <br>

  <div class="table">
    <table>
      <!--      1-->
      <tr>
        <td>お問い合わせ内容</td>
        <td>
          <div class="d-flex justify-content-around">
            <input type="radio" id="html" name="fav_language" value="HTML">
            <label for="html">最新の空室状況を知りたい</label><br>
            <input type="radio" id="html" name="fav_language" value="HTML">
            <label for="html">物件を実際に見たい</label><br>
            <input type="radio" id="html" name="fav_language" value="HTML">
            <label for="html">詳しく教えて欲しい</label><br>
          </div>
        </td>
      </tr>
      <!--      2-->
      <tr>
        <td>
          <div class="d-flex justify-content-between">
            <p>お名前</p>
            <p>必須</p>
          </div>
        </td>
        <td>
          <div class="d-flex justify-content-between">
            <label for="fname">姓</label>
            <input type="text" id="fname" name="fname" placeholder="例）　山田"><br><br>
            <label for="lname">名</label>
            <input type="text" id="lname" name="lname" placeholder="例）　太郎"><br><br>
          </div>
        </td>
      </tr>
      <!--      3-->
      <tr>
        <td>
          <div class="d-flex justify-content-between">
            <p>メールアドレス</p>
            <p>必須</p>
          </div>
        </td>
        <td>
          <div class="d-flex justify-content-center">
            <input type="text" id="fname" name="fname" placeholder="sumai@smocca.jp(半角英数字)"><br><br>
            <label for="lname">※半角英数字のみ</label>
          </div>
          <br>
          <ul>
            <li>
              ※電話番号のみでもお問い合わせが可能です。
            </li>
            <li>
              ※ご登録いただく電話番号は、LINE株式会社が提供する「通知メッセージ」というサービスで利用される可能性がございます。
            </li>
            <li>
              ※返信メールが受信可能なメールアドレスをご入力ください。
            </li>
            <li>
              ※ドメイン指定受信をご利用の方は、設定変更をお願いします。
            </li>
            <li>※メールアドレスと電話番号の入力が無い場合は<span class="typo_color_orange_a">キャンペーン対象外</span>となります。</li>
            <br>
            <div class="mt_10">
              <label class="cb_rd01 cb_rd_s25 cb_checked_gray"><input checked="checked" name="apply[alert_mail_flag]" type="checkbox" value="1" /><span>新着物件情報、お得な情報など賃貸SMOCCA!からのメールを受け取る</span></label>
              <span class="d_block typo_color_gray_a txt_size_12 mt_10">※ご希望条件に合わせたおすすめの最新物件情報をお届けします。ぜひご登録ください。</span>
              <span>
                ※ご希望条件に合わせたおすすめの最新物件情報をお届けします。ぜひご登録ください。
              </span>
            </div>
          </ul>
          <br>
        </td>
      </tr>
      <!--      4-->
      <tr>
        <td>
          <div class="d-flex justify-content-between">
            <p>電話番号</p>
            <p>任意</p>
          </div>
        </td>
        <td>
          <div>
            <ul>
              <input autocomplete="tel" class="input01 is_required w_200px input_tel js_apply_input" id="apply_tel" name="apply[tel]" placeholder="08012345678(半角)" type="tel">
              <br>
              <li>※メールアドレスと電話番号の入力が無い場合は<span>キャンペーン対象外</span>となります。</li>
            </ul>
          </div>
        </td>
      </tr>

      <!--      5-->
      <tr>
        <td>
          <div class="d-flex justify-content-between">
            <p>備考</p>
          </div>
        </td>
        <td>
          <div>
            <ul>
              <textarea cols="10" id="apply_memo" name="apply[memo]" placeholder="記入例）13時から14時の間に連絡がほしいです。" rows="5"></textarea>
              <span>※全角100文字以内</span>
            </ul>
          </div>
        </td>
      </tr>

      <!--      6-->
      <tr>
        <td>
          <div>
            <p>キャンペーンに関するご案内</p>
            <p>任意</p>
          </div>
        </td>
        <td>
          <ul>
            <label class="cb_rd01 cb_checked_gray">
              <input checked="checked" name="apply[lead_collaboration_status]" type="checkbox" value="1">
              <span>お引越し先でのライフラインのご案内を希望する。</span>
            </label>
            <p>※ライフラインのご案内を希望された方は「ＧＭＯインターネットグループ株式会社」よりお電話又はメールにてご連絡がございます。</p>
            <p><span>ＧＭＯインターネットグループ株式会社の個人情報の取扱について</span><br>ＧＭＯインターネットグループ株式会社に提供したお客様のお名前、メールアドレス、電話番号のなどの個人情報は、ＧＭＯインターネットグループ株式会社の責任・管理のもと、お申込みまたはご説明の際のご連絡方法として利用されます。</p>
          </ul>
        </td>
      </tr>
    </table>

    <button type="button">次へ</button>
  </div>

  <div>
    <i class="fas fa-cloud"></i>
    <span>他の物件も<span>同時にお問い合わせ</span>しませんか？ チェックを入れるだけで簡単お問い合わせ !</span>
    <p>平均<span>5</span>件のお問い合わせでご希望の物件が見つかりやすくなります♪</p>
  </div>
  <br><hr>

  <div>
    <h2>お問い合わせする物件に似ている物件があります。</h2>
    <div class="d_table w_100per mb_20 ws_nowrap">
      <div class="d_table_cell v_middle">
        <div class="d_table">
          <div class="d_table_cell v_middle">
            <div class="d_table pl_15 pr_15 pt_13 pb_10 box_br8_bw5_f0 b_width_3px">
              <span class="d_table_cell v_middle pr_5"><span class="icon_price"></span></span>
              <span class="d_table_cell v_middle txt_size_15">家賃：<span class="u-color-emphasis fw_bold">4万円</span>以内</span>
            </div>
          </div>
          <div class="d_table_cell v_middle pl_15 pr_15"><span class="icon_close txt_size_18 u-color-ccc"></span></div>
          <div class="d_table_cell v_middle">
            <div class="d_table pl_15 pr_15 pt_13 pb_10 box_br8_bw5_f0 b_width_3px">
              <span class="d_table_cell v_middle pr_5"><span class="icon_house"></span></span>
              <span class="d_table_cell v_middle pt_1">間取り：1R、1K、1DKなど</span>
            </div>
          </div>
        </div>
      </div>
      <div class="d_table_cell v_middle pl_10 w_100per">
        <p class="f_left txt_size_16 letter_0 fw_bold">のオススメ物件をご用意しました！</p>
      </div>
    </div>
    <button type="button">次へ</button>
  </div>
  <br><hr/>

  <div>
    <i class="fas fa-cloud"></i>
    <span>お問い合わせ物件・不動産会社</span>
    <p>以下の物件をお問い合わせいたします。問い合わせ先は<span>チェックの入っている取扱会社</span>です。</p>
  </div>
  <br><hr>

  <div>
    <div>
      <a href="https://smocca-staging.zigexn.vn/specific/terms" rel="nofollow" target="_blank" class="btn_link01">利用規約</a>および<a href="https://smocca-staging.zigexn.vn/specific/privacy" rel="nofollow" class="btn_link01" target="_blank">個人情報の取扱いについて</a>をご確認・ご同意の上、お問い合わせを継続してください。<br>
      メールアドレスと電話番号の入力が無い場合は<span class="typo_color_orange_a">キャンペーン対象外</span>となります。
    </div>

    <br>

    <p class="mt_20 mb_20">お問い合わせ内容がよろしければ、下部の「送信する」ボタンで問い合わせが完了します。</p>

    <br>
    <button type="button">お問い合わせ内容を送信する</button>
  </div>

</section>
<br><hr>

<footer>
  <div>
    <h3>個人情報取り扱いにつきまして</h3>
    <div>
      <div><img src="https://smocca-staging.zigexn.vn/assets/common/privacy_mark-4b33b464643e4a7090ce20bdcae048f4.png" alt="たいせつにします プライバシー" width="70"></div>
      <div>
        株式会社じげんはプライバシーマークを取得しています。
      </div>
    </div>
  </div>
  <img src="https://smocca-staging.zigexn.vn/assets/smocca/cashback/20231101/default/banner_cp760_01-732186c4f4dd31286d95194f1af2d5eb.png" alt="cashback">
</footer>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <%= link_to "Jobs App", root_path, class: "navbar-brand" %>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <% if current_user.is_admin? %>
            <li class="nav-item">
              <%= link_to "Jobs", jobs_path, class: "nav-link" %>
            </li>

            <li class="nav-item">
              <%= link_to "Organizations", organizations_path ,class: "nav-link" %>
            </li>
          <% end %>

          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "nav-link" %>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Welcome to <%= Rails.application.class.module_parent_name %>!</h1>
<%= render 'form' %>

app/views/jobs/_form.html.erb
<%= form_with(model: @job) do |form| %>
  <% if @job.errors.any? %>
    <div style="color: red">
      <h2>
        <% pluralize(@job.error.count, "error") %>prohibited this post from being saved:</h2>
      <ul>
        <% job.error.each do |error| %>
          <li><%= error.full_messages %>></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br/>

  <div class="form-group">
    <%= form.label :title%>
    <%= form.text_field :title, class: 'form-control', required: true, autofocus: true, placeholder: 'Junior Frontend Developer...' %>
  </div>
  <br/>

  <div class="form-group">
    <%= form.label :apply_url, 'Apply link' %>
    <%= form.text_field :apply_url, class: 'form-control', required: true, placeholder: 'https://...' %>
  </div>
  <br/>

  <div class="form-group">
    <%= form.label :level%>
    <%= form.select :level, %w[Fresher Junior Senior Leader Manger] %>
    <br/>
  </div>
  <br/>

  <div class="form-group">
    <%= form.label :job_type%>
    <%= form.select :job_type, %w[Full-time Part-time Contract Freelance] %>
    <br/>
  </div>
  <br/>

  <div class="form-group">
    <%= form.label :location %>
    <%= form.text_field :location, class: 'form-control', required: true, placeholder: 'Examples: "San Francisco, CA", "Seattle", "Anywhere"' %>
  </div>
  <br/>

  <div class="form-group">
    <%= form.label :remoteable %>
    <%= form.check_box :remoteable %>
    <i class="fa fa-wifi">Work can be done remotely</i>
  </div>
  <br/>

  <div class="form-group">
    <%= form.label :is_published%>
    <%= form.check_box :is_published %>
  </div>
  <br/>


  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, size: "60x10" %>
  </div>

  <br/><br/>

  <div class="action">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<p style="color: green"><%= notice %></p>
<% content_for :page_title, @job.title %>
<div class="card">
  <div class="card-header">
    <h1>Edit Job</h1>
  </div>
  <div class="card-body">
    <%= render 'form', post: @job %>
  </div>
</div>

<br/>
<div>
  <%= link_to "Back", jobs_path, class: "btn btn-secondary" %>
</div>
<br/>

app/views/jobs/index.html.erb
<p style="color: green"><%= notice %></p>
<% if user_signed_in? %>
  <h1 class="title">Jobs</h1>
  <br/><br/>

  <% @jobs.each do |job| %>
    <div class="row">
      <div class="card mb-3">
        <div class="card-body">
          <h5 class="card-title"><%= link_to job.title, job %></h5>
          <p class="card-text"><%= job.description %></p>
        </div>
      </div>
    </div>
  <% end %>
  <br/><br/>

  <%= link_to "New Job", new_job_path, class: 'btn btn-primary' %>

<% else %>

  <h1>Hello!</h1>
  <p>This is my New Jobs Board</p>

<% end %>

app/views/jobs/new.html.erb
<p style="color: green"><%= notice %></p>
<div class="card">
  <div class="card-header">
    <h2>Add New Job</h2>
  </div>
  <div class="card-body">
    <%= render 'form', job: @job %>
  </div>
</div>

<br/>
<div>
  <%= link_to "Back", jobs_path, class: "btn btn-secondary" %>
</div>

app/views/jobs/show.html.erb
<p style="color: green"><%= notice %></p>
<% content_for :page_title, @job.title %>
<section class="section header'">
  <div class="container">
    <h1><%= @job.title %></h1>
    <h5><%= @job.published_at %></h5>
    <h5><%= @job.level %></h5>
    <h5><%= @job.location %></h5>

    <br/><br/>

    <div class="col">
      <%= link_to "Edit", edit_job_path(@job), class: 'btn btn-primary' %>
      <%= link_to "Delete", @job, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'btn btn-danger' %>
    </div>
  </div>
</section>

<hr/><br/>

<section class="section content">
  <div class="container">
    <%= @job.description %>
  </div>
</section>

<br/>

<section class="section comments">
<!--  <div class="container">-->
<!--    <h2><strong><%#= @post.comments.count %></strong> Comments</h2>-->
    <%#= render 'comments/index', post: @post %>
<!--    <div class="comment-form mt-5">-->
<!--      <h2 class="subtitle is-3">Leave a comment</h2>-->
      <%#= render 'comments/form', object: [@post, @comment] %>
<!--    </div>-->
<!--  </div>-->
</section>

<br/>
<div class="container">
  <%= link_to "Back", jobs_path, class: "btn btn-secondary" %>
</div>

<br/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobsBoard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'home/header' %>
    <br/>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/organizations/_form.html.erb
<%= form_with(model: @organization) do |form| %>
  <% if organization.errors.any? %>
    <div style="color: red">
      <h2>
        <% pluralize(organization.error.count, "error") %>prohibited this post from being saved:</h2>
      <ul>
        <% job.error.each do |error| %>
          <li><%= error.full_messages %>></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br/>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control', required: true, autofocus: true, placeholder: 'Zigexn VeNtura' %>
  </div>
  <br/>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: 'form-control', required: true, placeholder: '131 Xo Viet Nghe Tinh, Binh Thanh,...' %>
  </div>
  <br/>

  <div class="form-group">
    <%= form.label :country %>
    <%= form.text_field :country, class: 'form-control', required: true, placeholder: 'Vietnam' %>
  </div>
  <br/>

  <div class="form-group">
    <%= form.label :tax_code%>
    <%= form.text_field :tax_code, required: true%>
    <br/>
  </div>
  <br/>

  <div class="form-group">
    <%= form.label :company_size %>
    <%= form.select :company_size, %w[5-10 11-50 51-100 Over100] %>
    <br/>
  </div>
  <br/>

  <div class="form-group">
    <%= form.label :working_days%>
    <%= form.select :working_days, %w[Monday-Friday Monday-Saturday Full] %>
    <br/>
  </div>
  <br/>

  <div class="form-group">
    <%= form.label :company_type%>
    <%= form.select :company_type, %w[Product Outsource] %>
    <br/>
  </div>
  <br/>

  <div class="form-group">
    <%= form.label :landing_page, 'Landing Page'%>
    <%= form.text_field :landing_page, class: 'form-control', placeholder: 'https://...' %>
  </div>
  <br/>

  <div class="form-group">
    <%= form.label :status%>
    <%= form.select :status, %w[Active Pending Inactive] %>
  </div>
  <br/>

  <div class="form-group">
    <%= form.label :ot_policy, 'OT Policy' %>
    <%= form.check_box :ot_policy %>
    <i class="fa fa-wifi">No OT</i>
  </div>
  <br/>

  <div class="form-group">
    <%= form.label :short_description %>
    <%= form.text_field :short_description, class: 'form-control', placeholder: 'Make things done,...' %>
  </div>
  <br/>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, size: "60x10" %>
  </div>

  <br/><br/>

  <div class="action">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<p style="color: green"><%= notice %></p>
<% content_for :page_title, @organization.name %>
<div class="card">
  <div class="card-header">
    <h1>Edit Organization</h1>
  </div>
  <div class="card-body">
    <%= render 'form', organization: @organization %>
  </div>
</div>

<br/>
<div>
  <%= link_to "Back", organizations_path, class: "btn btn-secondary" %>
</div>
<br/>

app/views/organizations/index.html.erb
<p style="color: green"><%= notice %></p>
<% if user_signed_in? %>
  <h1 class="title">Organizations</h1>
  <br/><br/>

  <% @organization.each do |organization| %>
    <div class="row">
      <div class="card mb-3">
        <div class="card-body">
          <h5 class="card-title"><%= link_to organization.name, organization %></h5>
          <p class="card-text"><%= organization.short_description %></p>
          <p class="card-text"><%= organization.address %></p>
        </div>
      </div>
    </div>
  <% end %>
  <br/><br/>

  <%= link_to "New Organization", new_organization_path, class: 'btn btn-primary' %>

<% else %>

  <h1>Hello!</h1>
  <p>This is my New Jobs Board</p>

<% end %>

app/views/organizations/new.html.erb
<p style="color: green"><%= notice %></p>
<div class="card">
  <div class="card-header">
    <h2>Add New Organization</h2>
  </div>
  <div class="card-body">
    <%= render 'form', organization: @organization %>
  </div>
</div>

<br/>
<div>
  <%= link_to "Back", organizations_path, class: "btn btn-secondary" %>
</div>

app/views/organizations/show.html.erb
<p style="color: green"><%= notice %></p>
<% content_for :page_title, @organization.name %>
<section class="section header'">
  <div class="container">
    <h1><%= @organization.name %></h1>
    <h5><%= @organization.short_description %></h5>
    <h5><%= @organization.address %></h5>
    <h5><%= @organization.country %></h5>
    <h5><%= @organization.tax_code %></h5>

    <br/><br/>

    <div class="col">
      <%= link_to "Edit", edit_organization_path(@organization), class: 'btn btn-primary' %>
      <%= link_to "Delete", @organization, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'btn btn-danger' %>
    </div>
  </div>
</section>

<hr/><br/>

<section class="section content">
  <div class="container">
    <%= @organization.description %>
  </div>
</section>

<br/>

<section class="section comments">
  <!--  <div class="container">-->
  <!--    <h2><strong><%#= @post.comments.count %></strong> Comments</h2>-->
  <%#= render 'comments/index', post: @post %>
  <!--    <div class="comment-form mt-5">-->
  <!--      <h2 class="subtitle is-3">Leave a comment</h2>-->
  <%#= render 'comments/form', object: [@post, @comment] %>
  <!--    </div>-->
  <!--  </div>-->
</section>

<br/>
<div class="container">
  <%= link_to "Back", organizations_path, class: "btn btn-secondary" %>
</div>

<br/>